### Portfolio Optimisation with Linear Algebra ###

This notebook pre-supposes some familiarity with linear algebra from school. But for the older among us, just to bring back some of the good ole memories, let's try to solve a set of linear equations.

In [2]:
import numpy as np

Let's solve the following equations:
* 2x + 3y + 4z = 11
* 10x + y + z = 32
* 5x + 7y + 8z = 20

We represent the equation above as Ax = b

In [3]:
A = np.array([[2, 3, 4], [10, 1, 1], [5, 7, 8]])
b = np.array([[11], [32], [20]])

In [6]:
A

array([[ 2,  3,  4],
       [10,  1,  1],
       [ 5,  7,  8]])

In [7]:
b

array([[11],
       [32],
       [20]])

And solve for x

In [8]:
x = np.linalg.solve(A, b)
x

array([[ 3.21621622],
       [-5.21621622],
       [ 5.05405405]])

### Linear Algebra for a Simple Portfolio Optimisation -  ###

We want to build a simplified portfolio of CASH, EQUITIES and BONDS.
The assumptions/constraints are that - 
* Proportion of CASH, EQUITIES, and BONDS should add up to 1 (i.e. 100%)
* The mix of CASH, EQUITIES and BONDS should give us a total return of 0.05 (i.e. 5%)
* CASH returns = 0.01, EQUITIES returns = 0.1, BOND returns = 0.05
* Proportion of CASH should be 0.2 (20%)

So the equations are -
- CASH + EQUITIES + BONDS = 1
- 0.01\*CASH + 0.1\*EQUITIES + 0.05\*BONDS = 0.05
- CASH = 0.2 

In [1]:
import numpy as np
A = np.array([[1,1,1], [0.01,0.1,0.05], [1,0,0]])
A

array([[ 1.  ,  1.  ,  1.  ],
       [ 0.01,  0.1 ,  0.05],
       [ 1.  ,  0.  ,  0.  ]])

In [2]:
B = np.array([1,0.05,0.2])
B

array([ 1.  ,  0.05,  0.2 ])

To solve and get the proportion of CASH, EQUITIES, and BONDS that we need to meet the constraints above

In [4]:
print(np.linalg.solve(A,B))

[ 0.2   0.16  0.64]


### Common Linear Algebra Operations ###

Other than the above, there are a range of linear algebra operations that we can undertake using Numpy

Dot product is just what we had learned in school. If you do not remember, it's basically the sum of row x col in each of the resultant cells

In [5]:
a = np.array([[1, 0],[0, 1]])
b = np.array( [[4, 1],[2, 2]])
print(a)
print(b)

[[1 0]
 [0 1]]
[[4 1]
 [2 2]]


So we take (1x4+0x2)=4 for the top left cell ...

In [6]:
np.dot(a,b)

array([[4, 1],
       [2, 2]])

In [7]:
# 1x3 + 1x5 + 1x1 = 9
a = np.array([1, 1, 1])
b = np.array([3, 5, 1])
np.inner(a,b)

9

In [8]:
# First row is 1x3, 1x5, 1x1; ditto for the rest
np.outer(a,b)

array([[3, 5, 1],
       [3, 5, 1],
       [3, 5, 1]])

In [9]:
# This is a L2-norm, basically the sq root of (0^2+1^2+2^2)
a = np.arange(3)
np.linalg.norm(a)

2.2360679774997898

In [10]:
# Det is ABS(A) = a*d - b*c; so here it is 1*4-2*3=4-6=2
a = np.array([[1,2],[3,4]])
np.linalg.det(a)

-2.0000000000000004

In [11]:
# for [[a,b],[c,d]], you switch a and d, make b and c negative and divide by the det 
a = np.array([[1,2],[3,4]])
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [12]:
# Decomposing a matrix into A = QR
a = np.array([[1,2],[3,4]])
np.linalg.qr(a)

(array([[-0.31622777, -0.9486833 ],
        [-0.9486833 ,  0.31622777]]), array([[-3.16227766, -4.42718872],
        [ 0.        , -0.63245553]]))

In [13]:
# Sum of the diagonal element
np.trace(np.arange(6).reshape(2,3))

4